---
- hosts: LAB
  become: yes

  tasks:
  - name: add tech user
    user:
      name: tech
      uid: 7000
      password: '*'
      expires: -1
      comment: "Konto techniczne"
      state: present

  - name: logowanie tylko po kluczach
    shell: usermod -p '*' tech

  - name: ustawienia waznosci hasla
    shell: chage -M -1 tech
    ignore_errors: true

  - name: ustawienie waznosci konta
    shell: chage -E -1 tech
    ignore_errors: true

  - name: utworzenie katalogu .ssh
    file: path=/home/tech/.ssh state=directory owner=tech group=tech mode=700

  - name: przeniesienie pliku authorized_keys  
    authorized_key:
      user: tech
      state: present
      key: "{{ lookup('file', 'tech.pub') }}"

#plik authorized_key musi znajdowac sie w katalogu files/ & folder files musi byc w lokalizacji, z której puszczany jest playbook
      
  - name: dodanie usera tech do crontab
    lineinfile:
      dest: /etc/cron.allow
      state: present
      insertafter: 'root'
      line: '{{ item.chain }}'
    with_items:
    - { chain: tech }
